import Head from "next/head";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import { Button } from "~/components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Family Tree</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative">
        <div>
          {" "}
          <div className="g-st absolute left-10 top-[-50px] z-0 h-60 w-60 rounded-full opacity-30"></div>
          <div className="g-st2 absolute right-28 top-12 z-0 h-60 w-60 rounded-full opacity-20"></div>
        </div>
        <div className="container absolute flex flex-col items-center justify-center gap-12 px-4 py-16">
          <div className="text-center">
            <h1 className="font-mono text-5xl font-extrabold tracking-tight text-stone-800 sm:text-[5rem]">
              Family Tree🌲
              <span className="border-2 border-black px-1 text-lg font-normal">
                Beta
              </span>
            </h1>
            <p className="pt-5 text-lg">
              Roots Unveiled: Your Family&apos;s Journey Begins Here
            </p>
          </div>

          <Button
            asChild
            variant={"outline"}
            className="border-stone-900 duration-100 ease-linear hover:scale-110"
          >
            <Link href="/fam-to-fam/famId">Get Started</Link>
          </Button>
        </div>
        <Toaster />
      </main>
    </>
  );
}
